weights: /root/autodl-tmp/yolov7-prune-main-1/runs/compress/slim-F-10-2.5-1/weights/best.pt
cfg: cfg/training/10.yaml
data: data/my_data.yaml
hyp: data/hyp.scratch.p5.yaml
epochs: 200
batch_size: 64
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 4
project: runs/train_distill
entity: null
name: slim4_all_1.3-2-1
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
prune_model: true
teacher_weights: /root/autodl-tmp/yolov7-prune-main-1/runs/compress/slim-F-10-1.3-1/weights/best.pt
teacher_cfg: cfg/training/10.yaml
kd_loss_type: all
kd_loss_decay: cosine_epoch
logical_loss_type: AlignSoftTarget
logical_loss_ratio: 0.12
teacher_kd_layers: 22,25,26,27
student_kd_layers: 22,25,26,27
feature_loss_type: cwd
feature_loss_ratio: 0.0088
world_size: 1
global_rank: -1
save_dir: runs/train_distill/slim4_all_1.3-2-12
total_batch_size: 64
